//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsFacilityManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int transactiondetailid { get; set; }
        public int transactionid { get; set; }
        public int facilityid { get; set; }
        public int timeslotid { get; set; }
        public System.DateTime date { get; set; }
        public int subfacilityid { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual SubFacility SubFacility { get; set; }
        public virtual Timeslot Timeslot { get; set; }
        public virtual TransactionDetail TransactionDetails1 { get; set; }
        public virtual TransactionDetail TransactionDetail1 { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
